# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .organizations.client import AsyncOrganizationsClient, OrganizationsClient
from .saml_connections.client import AsyncSamlConnectionsClient, SamlConnectionsClient
from .scim_directories.client import AsyncScimDirectoriesClient, ScimDirectoriesClient
from .setup_urls.client import AsyncSetupUrlsClient, SetupUrlsClient


class ManagementClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.organizations = OrganizationsClient(client_wrapper=self._client_wrapper)
        self.saml_connections = SamlConnectionsClient(client_wrapper=self._client_wrapper)
        self.scim_directories = ScimDirectoriesClient(client_wrapper=self._client_wrapper)
        self.setup_urls = SetupUrlsClient(client_wrapper=self._client_wrapper)


class AsyncManagementClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.organizations = AsyncOrganizationsClient(client_wrapper=self._client_wrapper)
        self.saml_connections = AsyncSamlConnectionsClient(client_wrapper=self._client_wrapper)
        self.scim_directories = AsyncScimDirectoriesClient(client_wrapper=self._client_wrapper)
        self.setup_urls = AsyncSetupUrlsClient(client_wrapper=self._client_wrapper)
